# change the followings to match your Github username and repo name
# baseurl: "munsonrobl.github.io" # the name of your github repo
# url: "https://munsonrobl.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Tailpages: Tailwind + Github Pages"
description: A Github Pages (Jekyll) template based on TailwindCSS

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Rob Munson
author-bio: Lead Software Engineer  # change to false to hide
author-image: profile.jpeg  # file must be in the /assets/img/ folder
author-avatar: 279.png

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Code
  permalink: code
- text: Coffee
  permalink: coffee
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: https://github.com/munsonrobl/
linkedin: https://linkedin.com/in/rob-munson
strava: https://www.strava.com/athletes/3084035
banana: false
medium: false
email: robmunson@gmail.com

# # footer information
footer-msg: "Made with Jekyll + Tailwind + GitHub pages"
footer-msg-link: https://linkedin.com/in/rob-munson

# # google analytics
# google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
